[package]
name = "rust"
version = "0.1.0"
authors = ["karoberts <cppwriter@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rust-crypto = "0.2.36"
